### ISSUE TITLE
Publish jhwbus jars

### ISSUE THREAD

**Issue by AnneThKu** [org-arl/jhwbus#5]

**Comment by notthetup** [comment]
One issue with this is we have OS and Architecture specific builds. We need to figure out how we can manage that effectively.

**Comment by notthetup** [comment]
Thinking about this, it might be easier to convert `jhwbus` to a pure gradle build and then use it as a source dependency against tags.. https://blog.gradle.org/introducing-source-dependencies

**Comment by mchitre** [comment]
Nice! That could work well.
